spring:
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

jwt:
  key: secret
  token:
    issuer: test
    duration: 10000 # 10 seconds